config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  get 'venues/:id/view' => 'venues#view', as: :venue_view
  post 'venues/:id/available' => 'venues#available', as: :venue_available
  get 'venues/:id/make_reservation' => 'venues#make_reservation',
      as: :venue_make_reservationget
  post 'venues/:id/make_reservation' => 'venues#make_reservation',
       as: :venue_make_reservation

  get 'venues/:id/make_unpaid_reservation' => 'venues#make_unpaid_reservation',
      as: :venue_make_unpaid_reservationget
  post 'venues/:id/make_unpaid_reservation' => 'venues#make_unpaid_reservation',
       as: :venue_make_unpaid_reservation

  get 'venues/:id/court_price_at' => 'venues#court_price_at',
      as: :court_price_at
  get 'venues/:id/manage_venue' => 'venues#courts_and_prices',
      as: :courts_and_prices

  post '/search' => 'pages#search', as: :search
  get '/search' => 'pages#search', as: :searchget

  get "search_venues" => "search#show", as: :search_venues
  get 'venues/:id/cancelled_reservations' => 'venues#cancelled_reservations', as: :venue_cancelled_reservations



  get 'venues/:id/memberships' => 'venues#memberships', as: :memberships

  get 'users/:id/invoices' => 'users#invoices', as: :user_invoices

  root 'pages#home'

  get '/search' => 'pages#search'
  post '/search' => 'pages#search'

  namespace :api do
    post 'authenticate' => 'auth#authenticate'
    get "sort_by_sport" => "venues#sort_by_sport"
    resources :users, only: [:create, :update] do
      get 'game_pass_check'

      collection do
        post :confirm_account
        post :reset_password
        get :email_check
      end
    end
    resources :companies, only: [] do
      post 'send_support_email'
    end
    get 'search' => 'venues#search'
    get 'all_sport_names' => 'venues#all_sport_names'
    resources :cards, only: [:create, :index]
    resources :reservations, only: [:create, :index, :destroy]
    resources :subscriptions, only: [:index]
    resources :venues, only: [:show, :index] do
      get 'users'
      get 'utilization_rate'
      get 'available_courts'
    end
    resources :game_passes, only: [:index, :show, :create, :update, :destroy] do
      collection do
        get :court_sports
        get :court_types
        get :templates
        get :available
      end
    end
  end

  post '/connect/managed' => 'stripe#managed', as: 'stripe_managed'

  devise_for :admins,
             controllers: { confirmations: 'confirmations' }

  devise_for  :users,
              path: '',
              path_names: { sign_in: 'login',
                            sign_out: 'logout',
                            edit: 'profile' },
              controllers: { omniauth_callbacks: 'api/omniauth_callbacks',
                             registrations: 'registrations',
                             confirmations: 'confirmations' }

  devise_scope :user do
    patch '/users/confirm' => 'confirmations#confirm',
          as: :user_confirm
    patch 'users/update_password' => 'registrations#update_password'
  end

  devise_scope :admin do
    patch '/admins/confirm' => 'confirmations#confirm',
          as: :admin_confirm
    authenticate :admin, lambda { |admin| admin.god? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  resources :users, only: [:show] do
    post 'add_card' => 'stripe#add_card', as: :add_card
    post 'card_reminder'
    post 'assign_discount', as: :assign_discount
    get  'recurring_reservations', on: :member
  end

  resources :companies do
    resources :admins, expect: [:new, :show]
    get :reports
    post :create_report
    get :report
    resources :invoices do
      collection do
        post :create_drafts
        post :send_all
        post :mark_paid
        post :destroy_all
        post :create_report
      end
    end
    get 'revenue' => 'dashboard#revenue', as: :revenue
    get 'resv' => 'dashboard#resv'
    member do
      post 'import_customers'
      get  'customers_csv_template'
    end
  end
  resources :invoices, only: [:show] do
    resources :invoice_components
    resources :custom_invoice_components
  end

  get 'companies/:id/customers' => 'companies#customers', as: :company_customers
  get 'venues/:id/map_users' => 'venues#map_users', as: :map_users

  resources :memberships, only: [:create] do
    collection do
      post :import
      get :csv_template
    end
  end

  resources :venues do
    resources :game_passes
    resources :prices, except: [:index, :new, :edit] do
      member do
        post :merge_conflicts
      end
    end
    resources :courts do
    end
    resources :reservations do
      get 'new_cart', on: :collection
      get  'resell_to_user_form', on: :member
      post 'resell_to_user', on: :member
    end
    resources :memberships, except: [:new, :edit, :update]
    get 'memberships/:id/convert_to_cc' => 'memberships#convert_to_cc', as: :convert_to_cc
    post 'memberships/:id' => 'memberships#update'
    get 'offdays'
    resources :day_off, only: [:create, :destroy]
    get 'court_modal/:id' => 'venues#court_modal', as: :court_modal
    get 'price_modal/:id' => 'venues#price_modal', as: :price_modal
    get 'closing_hours'
    get 'booking_ahead_limit'
    get 'active_courts'
    post 'change_listed' => 'venues#change_listed', as: :change_listed
    member do
      get 'reports'
      post 'booking_sales_report'
      get 'available_court_indexes'
    end
    resources :discounts, except: [:new]
    get 'manage_discounts', as: :manage_discounts
    get 'edit_emails'
    post 'update_emails'
    resources :photos, only: [:create, :destroy] do
      post 'make_primary'
    end
    resources :email_lists do
      post 'remove_users'
      post 'add_users'
      get 'off_list_users'
    end
  end

  post '/custom_mail(.:format)' => 'email_lists#custom_mail'
  get 'reservations/:id/cancel' => 'reservations#refund', as: :reservation_refund
  get 'reservations/:id/cancel_reservation' => 'reservations#cancel', as: :reservation_cancel
  get 'reservations/:id/resell' => 'reservations#resell', as: :reservation_resell
  get 'reservations/:id/show_log' => 'reservations#show_log', as: :reservation_show_log
  get '/privacypolicy', :to => redirect('/privacypolicy.html')
  get '/termsofuse', :to => redirect('/termsofuse.html')
end

app/models/user.rb
class User < ActiveRecord::Base
  include OmniauthRegisterable
  include CreditCards
  
  has_many :reservations, as: :user
  has_many :memberships
  has_many :venue_user_connectors, dependent: :destroy
  has_many :venues, through: :venue_user_connectors
  has_many :invoices
  has_many :discounts, through: :discount_connections
  has_many :discount_connections, dependent: :destroy
  has_many :email_list_user_connectors, dependent: :destroy
  has_many :email_lists, through: :email_list_user_connectors
  has_many :game_passes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable

  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, uniqueness: true

  # credit:
  # https://github.com/plataformatec/devise/wiki/How-To:-Find-a-user-when-you-have-their-credentials
  def self.authenticate(email, password)
    user = User.find_for_authentication(email: email)
    (user && user.valid_password?(password)) ? user : nil
  end

  def tz
    # TimeZone[self.timezone] || Time.zone
    Time.zone # TODO: change me to ActiveSupport::TimeZone with actual user timezone in the future
  end

  def outstanding_balance(company=nil)
    return 0.0 if !company.present?
    reservation_balance = company.reservations.where(user:self).where(is_billed: false).where(is_paid: false).sum(:price)
    game_pass_balance = company.game_passes.where(user:self).where(is_billed: false).where(is_paid: false).sum(:price)

    reservation_balance.to_f + game_pass_balance.to_f
  end

  def has_stripe?
    return self.stripe_id != nil
  end

  def has_game_pass?(venue)
    if self.game_passes.where(venue_id:venue.id).present?
      return true
    else
      return false
    end
  end

  def add_stripe_id(token)
    customer = Stripe::Customer.create(
      source: token,
      description: "Playven User"
    )
    self.update(stripe_id: customer.id)
  end

  def to_s
    "#{first_name} #{last_name}"
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def get_billing_address
    street_address.to_s + ' ' + zipcode.to_s + ' ' + city.to_s
  end

  # return discount or nil
  def discount_for(venue_id)
    @discounts_by_venue ||= discounts.group_by(&:venue_id)
    @discounts_by_venue[venue_id] ? @discounts_by_venue[venue_id].first : nil
  end

  def self.from_omniauth(auth)
    user_by_email = User.where(email: auth.info.email).first

    if user_by_email
      return user_by_email
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.first_name = auth.info.first_name
        user.last_name = auth.info.last_name
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.image = auth.info.image
        user.password = Devise.friendly_token[0,20]
      end
    end
  end

  def password_required?
    super if confirmed?
  end

  def password_match?
    errors[:password] << "can't be blank" if password.blank?
    errors[:password_confirmation] << "can't be blank" if password_confirmation.blank?
    errors[:password_confirmation] << "does not match password" if password != password_confirmation
    password == password_confirmation && !password.blank?
  end

  def venue_discount(venue)
    discounts.find { |discount| discount.venue == venue }
  end

  def mixpanel_params
    {
      '$email'           => email,
      '$created'         => created_at,
      '$first_name'      => first_name,
      '$last_name'       => last_name,
      'id'               => id,
      'sign_in_count'    => sign_in_count,
      'last_sign_in'     => current_sign_in_at
    }
  end

  def future_reservations
    reservations.non_recurring.future
  end

  def past_reservations
    reservations.non_recurring.past
  end

  def future_memberships
    reservations.recurring.future
  end

  def past_memberships
    reservations.recurring.past
  end

  def reselling_memberships
    reservations.recurring.reselling
  end

  def resold_memberships
    Reservation.where(initial_membership_id: memberships.map(&:id))
  end

  def assign_discount(discount)
    old_discount = discounts.find_by(venue_id: discount.venue_id)
    discounts.delete(old_discount.id) if old_discount
    discounts << discount
  end

  def unconfirmed?
    !confirmed?
  end

  def self.find_or_create_by_id(user_params)
    if user_params[:user_id]
      User.find(user_params[:user_id])
    else
      User.find_or_create_by(email: user_params[:email]) do |user|
        user.assign_attributes(user_params.permit(:first_name, :last_name,
                                                  :email, :phone_number, :city,
                                                  :street_address, :zipcode))
        user.skip_confirmation_notification!
      end
    end
  end

  def self.search(query)
    query = "%#{query.to_s.strip}%"
    if query.present?
      full_name = Arel::Nodes::NamedFunction.new(
        'concat',
        [arel_table[:first_name],
        Arel::Nodes.build_quoted(' '),
        arel_table[:last_name]]
      )
      phone = Arel::Nodes::NamedFunction.new(
        "CAST",
        [arel_table[:phone_number].as("TEXT")]
      )
      where(full_name.matches(query)
              .or(arel_table[:email].matches(query))
              .or(phone.matches(query)))
    else
      all
    end
  end
end

app/controllers/api/users_controller.rb
class API::UsersController < API::BaseController

  before_action :validate_confirmed_user, only: [:create]
  before_action :authenticate_request!, only: [:update]

  def create
    user = User.new(user_params)
    if user.save
      render json: { auth_token: AuthToken.encode(JSON.parse(user.to_json)) }
    else
      render json: { errors: user.errors.full_messages }, status: 422
    end
  end
  
  def email_check
    if params[:email].blank?
      render json: { message: I18n.t('api.users.email_check.email_required') }, status: 422
    elsif User.find_by_email(params[:email])
      render json: { message: I18n.t('api.users.email_check.success') }, status: 200
    else
      # Is rendered for both invalid Email Parameter and when no User is found
      render json: { message: I18n.t('api.users.email_check.error') }, status: 422
    end
  end

  def confirm_account
    if user_confirmation_params[:email].blank?
      render json: { message: I18n.t('api.users.confirm_account.email_required') }, status: 422
    elsif User.send_confirmation_instructions(user_confirmation_params)
      render json: { message: I18n.t('api.users.confirm_account.success') }, status: 200
    else
      render json: { message: I18n.t('api.users.confirm_account.error') }, status: 422
    end
  end

  def update
    user_params.delete(:email)

    if user_params[:password].present? && user_params[:current_password].blank? || user_params[:password].blank? && user_params[:current_password].present?
      render json: { message: I18n.t('api.users.errors.passwords_required') }, status: 422
    elsif user_params[:current_password] && user_params[:password] && @current_user.update_with_password(user_params)
      render json: { message: I18n.t('api.users.password_updated') }, status: 200
    elsif user_params[:password].blank? && user_params[:current_password].blank? && @current_user.update_without_password(user_params)
      render json: { message: I18n.t('api.users.profile_updated') }, status: 200
    else
      render json: { message: @current_user.errors.full_messages }, status: 422
    end
  end

  def reset_password
    user = User.send_reset_password_instructions(email: params[:email])

    if user.valid?
      render json: { message: I18n.t('api.users.reset_password_email') }, status: 200
    else
      render json: { message: user.errors.full_messages.join(', ') }, status: 404
    end
  end

  def game_pass_check
    user     = User.find(params[:user_id])
    venue    = Venue.find(params[:venue_id])
    @check   = user.has_game_pass?(venue)
    @charges = user.game_passes.where(venue_id:venue.id).first.try(:remaining_charges)
  end

  private

  def validate_confirmed_user
    user = User.find_by_email(params[:email])
    if user.present? && user.encrypted_password.blank? && user.unconfirmed?
      render json: { error: 'unconfirmed_account', message: I18n.t('api.users.not_confirmed') }, status: 422
    elsif user.present? && user.encrypted_password.present? && user.unconfirmed?
      render json: { error: 'already_exists', message: I18n.t('api.users.already_exists') }, status: 422
    end
  end

  def user_params
    json_params_for(
      required: :user,
      permitted: [:city, :email, :first_name, :image, :last_name, :password, :password_confirmation, :phone_number, :provider, :street_address, :stripe_id, :uid, :zipcode, :current_password]
    )
  end

  def user_confirmation_params
    json_params_for(required: :user, permitted: [:email])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @mode = params[:mode]

    @reservations = case @mode
    when 'future'
      current_user.future_reservations.include_venues.order(start_time: :asc)
    when 'past'
      current_user.past_reservations.include_venues.order(start_time: :desc)
    else
      @mode = 'future'
      current_user.future_reservations.include_venues.order(start_time: :asc)
    end
    render :layout => "newlayout"
  end

  def recurring_reservations
    @user = current_user
    @mode = params[:mode]
    @recurring = true

    @reservations = case @mode
    when 'future'
      current_user.future_memberships.include_venues.order(start_time: :asc)
    when 'past'
      current_user.past_memberships.include_venues.order(start_time: :desc)
    when 'reselling'
      current_user.reselling_memberships.include_venues.order(start_time: :desc)
    when 'resold'
      current_user.resold_memberships.include_venues.order(start_time: :desc)
    else
      @mode = 'future'
      current_user.future_memberships.include_venues.order(start_time: :asc)
    end
    render 'show', :layout => "newlayout"
  end

  def invoices
    @user = current_user
    @reservations = current_user.reservations.where('start_time > ?', DateTime.now).order(start_time: :asc)
    @invoices = current_user.invoices
    @mode = params[:mode]
    case @mode
    when 'unpaid'
      @invoices = @invoices.unpaid
    when 'paid'
      @invoices = @invoices.paid
    else
      @mode = 'unpaid'
      @invoices = @invoices.unpaid
    end
  end

  def assign_discount
    user = User.find(params[:user_id])
    if params[:discount_create]
      user.assign_discount(Discount.find(params[:discount_id]))
    else
      user.discounts.delete(params[:discount_id])
    end
    render nothing: true
  end

  def card_reminder
    user = User.find(params[:user_id])
    venue = Venue.find(params[:venue_id])
    UserMailer.membership_card_reminder(user, venue).deliver_now
    redirect_to memberships_path(venue)
  end
end

app/views/users/_credit_cards.html.erb
<select class="select2_payment form-control" id="cardSelect" name="card">
  <option value="" disabled><%= t('.default_option') %></option>
  <% cards.each do |card| %>
    <option value="<%= card.id %>" data-code="<%= card.last4 %>"><%= card.brand %> <%= t('.ending_message', date: card.last4) %></option>
  <% end %>
</select>

app/views/users/_user_no_password.html.erb
<div id='new-user'>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <label class=""><%= t('.first_name')%></label>
        <input type="text" class="form-control" placeholder="<%= t('.first_name')%>"  name="user[first_name]" disabled required/>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <label class="control-label"><%= t('.last_name')%></label>
        <input type="text" class="form-control" placeholder="<%= t('.last_name')%>"  name="user[last_name]" disabled required/>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <label class="control-label"><%= t('.email')%></label>
        <input type="text" class="form-control" placeholder="<%= t('.email')%>"  name="user[email]" disabled required/>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <label class="control-label"><%= t('.phone_number')%></label>
        <input type="text" class="form-control"  placeholder='<%= t('.phone_number') %>' name="user[phone_number]" disabled  />
      </div>
    </div>
  </div>
</div>

app/views/users/invoices.html.erb
<%= render 'shared/newnav' %>

<main class="profile">
  <div class="row">
    <div class="col-xs-16 col-sm-12 col-sm-offset-2">
      <div class="profile__header">
        <div class="row">
          <div class="col-xs-16 col-sm-10">
            <div class="profile__photo">
              <%= image_tag 'users/profile.png' %>
            </div>
            <div class="profile__name">
              <div class="profile__name-primary"><%= t('.header')%></div>
              <div class="profile__name-full"><%= @user.first_name %> <%= @user.last_name %></div>
            </div>
          </div>
        </div>
      </div>
      <div class="profile__navs">
        <div class="profile__navs-link "><%= link_to t('.edit_profile'), edit_user_registration_path(current_user) %></div>
        <div class="profile__navs-link "><%= link_to t('.my_reservations'), user_path(current_user) %></div>
        <div class="profile__navs-link active"><%= link_to t('.invoices'), user_invoices_path(current_user) %></div>

        <div class="profile__navs-right">
          <div class="profile__navs-link"><a href="?mode=unpaid" class="<%= "active" if @mode == "unpaid"%>"><%= t('.unpaid')%></a></div>
          <div class="profile__navs-link"><a href="?mode=paid" class="<%= "active" if @mode == "paid"%>"><%= t('.paid')%></div>
        </div>

      </div>
      <div class="profile-invoices">
        <% @invoices.where(is_draft: false).where(is_paid: false).each do |i| %>

        <div class="profile-invoices__one">
          <div class="profile-invoices__title">
            <div class="profile-invoices__title-container">
              <div class="row">
                <div class="col-sm-16 col-md-8">
                  <div class="profile-invoices__title-date"><b><%= t('.title_date', date: (i.created_at + 2.weeks).strftime("%d/%m/%Y")) %></b></div>
                </div>
                <div class="col-sm-16 col-md-8">
                  <div class="profile-invoices__title-price"><b><%= number_to_currency(i.total) %></b></div>
                </div>
              </div>
            </div>

          </div>

          <div class="profile-invoices__content">
            <div class="row">
              <div class="col-sm-16 col-md-8">
                <div class="profile-invoices__place"><%= i.company.company_legal_name %></div>
                <div class="profile-invoices__status"><%= t('.membership') %></div>
                <div class="profile-invoices__contacts">
                  <div class="profile-invoices__phone"><span class="icon-phone"></span><%= i.company.company_phone %></div>
                  <div class="profile-invoices__email"><span class="icon-mail"></span>invoices@ampersports.com</div>
                </div>
              </div>
              <div class="col-sm-16 col-md-8 col-lg-6">
                <div class="btn-choose btn-choose_vertical btn-choose_dark">
                  <button class="btn btn-primary btn_lg"><%= t('.pay_now_button') %></button>
                  <div class="btn-choose__or"><%= t('support.or')%></div>
                  <%= link_to t('.download_invoice'), company_invoice_path(i.company, i, format: :pdf), class: "btn btn-success btn_lg" %>
                </div>
              </div>
            </div>

          </div>

          <div class="profile-invoices__info venue">
            <div class="venue-invoice">
              <div class="venue-invoice__logo"></div>
              <div class="venue-invoice__name"><%= t('.invoice_name_html', num: i.id) %></div>
            </div>
            <div class="venue-overlay">
              <h4 class="venue-title"><%= t('.invoice_info')%></h4>
              <div>
                <div class="venue-attr">
                  <div class="venue-attr_img icon-map-xs"></div>
                  <div class="venue-attr_text"><%= i.company.company_street_address %><br><%= i.company.company_zip %> <%= i.company.company_city%></div>
                </div>
                <div class="venue-attr">
                  <div class="venue-attr_img icon-site"></div>
                  <a class="venue-attr_text" href=""><%= i.company.company_website %></a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</main>
<%= render 'layouts/footer' %>

app/views/users/show.html.erb
<%= render 'shared/newnav' %>
<%= render 'shared/message' %>

<main class="profile">
  <div class="row">
    <div class="col-xs-16 col-sm-12 col-sm-offset-2">
      <div class="profile__header">
        <div class="row">
          <div class="col-xs-16 col-sm-10">
            <div class="profile__photo">
              <%= image_tag 'users/profile.png' %>
            </div>
            <div class="profile__name">
              <div class="profile__name-primary"><%= t('.header') %></div>
              <div class="profile__name-full"><%= @user.first_name %> <%= @user.last_name %></div>
            </div>
          </div>
          <div class="col-xs-16 col-sm-6">
          </div>
        </div>
      </div>
      <div class="profile__navs">

        <div class="profile__navs-link"><%= link_to t('.edit_profile'), edit_user_registration_path(current_user) %></div>
        <div class="profile__navs-link <%= "active" if !@recurring %>"><%= link_to t('.my_reservations'), user_path(current_user)  %></div>
        <div class="profile__navs-link <%= "active" if @recurring %>"><%= link_to t('.my_recurring_reservations'), recurring_reservations_user_path(current_user)  %></div>
        <div class="profile__navs-link"><%= link_to t('.invoices'), user_invoices_path(current_user)  %></div>

        <div class="profile__navs-right">
          <div class="profile__navs-link"><a href="?mode=past" class="<%= "active" if @mode == "past"%>"><%= t('.past_reservations')%></a></div>
          <div class="profile__navs-link"><a href="?mode=future" class="<%= "active" if @mode == "future"%>"><%= t('.future_reservations') %></a></div>
          <% if @recurring %>
            <div class="profile__navs-link"><a href="?mode=reselling" class="<%= "active" if @mode == "reselling"%>"><%= t('.reselling_reservations')%></a></div>
            <div class="profile__navs-link"><a href="?mode=resold" class="<%= "active" if @mode == "resold"%>"><%= t('.resold_reservations') %></a></div>
          <% end %>
        </div>

      </div>

      <div class="profile-reservations">
        <% @reservations.each do |r| %>
          <div class="profile-reservations__one profile-reservations__one_tennis">
            <div class="row">
              <div class="col-sm-16 col-md-8 padding-0">
                <div class="venue profile-reservations__photo">
                  <%= link_to (image_tag(r.court.venue.try_photo_url)), venue_path(r.court.venue[:id]) %>
                  <div class="venue-overlay">
                    <h4 class="venue-title">info</h4>
                    <div>
                      <div class="venue-attr">
                        <div class="venue-attr_img icon-map-xs"></div>
                        <div class="venue-attr_text"> <%= r.court.venue.street %>,
                          <br><%= r.court.venue.zip %> <%= r.court.venue.city %></div>
                      </div>
                      <div class="venue-attr">
                        <div class="venue-attr_img icon-phone"></div>
                        <a class="venue-attr_text" href=""><%= r.court.venue.phone_number %></a>
                      </div>
                      <div class="venue-attr">
                        <div class="venue-attr_img icon-site"></div>
                        <a class="venue-attr_text" href=""><%= r.court.venue.website %></a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-sm-16 col-md-8 padding-0">
                <div class="profile-reservations__time">
                  <div class="profile-reservations__time-left"><%= TimeSanitizer.output(r.start_time).try(:strftime, '%B') %> <b><%= TimeSanitizer.output(r.start_time).try(:strftime, '%d') %></b> <%= TimeSanitizer.output(r.start_time).try(:strftime, '%Y') %> <% if r.refunded %> <b><%= t('.cancelled') %></b> <% end %></div>
                  <div class="profile-reservations__time-right"><%= r.court.sport %></div>
                </div>
                <div class="profile-reservations__content">
                  <div class="profile-reservations__content-title"><%= link_to r.court.venue.venue_name, venue_path(r.court.venue[:id])  %></div>
                  <div class="profile-reservations__content-subtitle"><%= r.court.court_name %></div>
                  <div class="profile-reservations__content-time"><span class="icon-clock icon-clock_blue"></span> <%= TimeSanitizer.output(r.start_time).try(:strftime, '%H:%M') %> - <%= TimeSanitizer.output(r.end_time).try(:strftime, '%H:%M')%></div>
                  <div class="profile-reservations__content-price">
                    <span class="text-primary">€</span><%= number_to_currency(r.price) %> | 
                    <% if r.reselling? %>
                      <%= t('.reservation_reselling') %>
                    <% elsif r.payment_type == "paid" %>
                      <%= t('.reservation_paid') %>
                    <% elsif r.payment_type == "unpaid" %>
                      <%= t('.reservation_unpaid') %>
                    <% end %>
                  </div>
                  <% if r.user_id == current_user.id %>
                    <div class="profile-reservations__content-action">
                      <span>
                        <% if @recurring %>
                          <% if r.reselling? %>
                            <%= link_to t('.withdraw_resell_reservation_link'), reservation_resell_path(r) %>
                          <% elsif r.future? %>
                            <%= link_to t('.resell_reservation_link'), reservation_resell_path(r) %>
                          <% else %>
                            <%= t('.cant_resell_reservation_message')%>
                          <% end %>
                        <% else %>
                          <% if r.refundable? %>
                            <%= link_to t('.cancel_reservation_link'), reservation_refund_path(r) %>
                          <% elsif r.cancelable?  %>
                            <%= link_to t('.cancel_reservation_link'), reservation_cancel_path(r) %>
                          <% else %>
                            <%= t('.cant_cancel_reservation_message')%>
                          <% end %>
                        <% end %>
                      </span>
                      <span class="profile-reservations__content-action-sep">|</span>
                      <span><%= link_to t('.add_to_calendar'), venue_reservation_path(r.court.venue.id, r.id, format: :ics) %></span>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

<%= render 'layouts/footer' %>