config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  get 'venues/:id/view' => 'venues#view', as: :venue_view
  post 'venues/:id/available' => 'venues#available', as: :venue_available
  get 'venues/:id/make_reservation' => 'venues#make_reservation',
      as: :venue_make_reservationget
  post 'venues/:id/make_reservation' => 'venues#make_reservation',
       as: :venue_make_reservation

  get 'venues/:id/make_unpaid_reservation' => 'venues#make_unpaid_reservation',
      as: :venue_make_unpaid_reservationget
  post 'venues/:id/make_unpaid_reservation' => 'venues#make_unpaid_reservation',
       as: :venue_make_unpaid_reservation

  get 'venues/:id/court_price_at' => 'venues#court_price_at',
      as: :court_price_at
  get 'venues/:id/manage_venue' => 'venues#courts_and_prices',
      as: :courts_and_prices

  post '/search' => 'pages#search', as: :search
  get '/search' => 'pages#search', as: :searchget

  get "search_venues" => "search#show", as: :search_venues
  get 'venues/:id/cancelled_reservations' => 'venues#cancelled_reservations', as: :venue_cancelled_reservations



  get 'venues/:id/memberships' => 'venues#memberships', as: :memberships

  get 'users/:id/invoices' => 'users#invoices', as: :user_invoices

  root 'pages#home'

  get '/search' => 'pages#search'
  post '/search' => 'pages#search'

  namespace :api do
    post 'authenticate' => 'auth#authenticate'
    get "sort_by_sport" => "venues#sort_by_sport"
    resources :users, only: [:create, :update] do
      get 'game_pass_check'

      collection do
        post :confirm_account
        post :reset_password
        get :email_check
      end
    end
    resources :companies, only: [] do
      post 'send_support_email'
    end
    get 'search' => 'venues#search'
    get 'all_sport_names' => 'venues#all_sport_names'
    resources :cards, only: [:create, :index]
    resources :reservations, only: [:create, :index, :destroy]
    resources :subscriptions, only: [:index]
    resources :venues, only: [:show, :index] do
      get 'users'
      get 'utilization_rate'
      get 'available_courts'
    end
    resources :game_passes, only: [:index, :show, :create, :update, :destroy] do
      collection do
        get :court_sports
        get :court_types
        get :templates
        get :available
      end
    end
  end

  post '/connect/managed' => 'stripe#managed', as: 'stripe_managed'

  devise_for :admins,
             controllers: { confirmations: 'confirmations' }

  devise_for  :users,
              path: '',
              path_names: { sign_in: 'login',
                            sign_out: 'logout',
                            edit: 'profile' },
              controllers: { omniauth_callbacks: 'api/omniauth_callbacks',
                             registrations: 'registrations',
                             confirmations: 'confirmations' }

  devise_scope :user do
    patch '/users/confirm' => 'confirmations#confirm',
          as: :user_confirm
    patch 'users/update_password' => 'registrations#update_password'
  end

  devise_scope :admin do
    patch '/admins/confirm' => 'confirmations#confirm',
          as: :admin_confirm
    authenticate :admin, lambda { |admin| admin.god? } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

  resources :users, only: [:show] do
    post 'add_card' => 'stripe#add_card', as: :add_card
    post 'card_reminder'
    post 'assign_discount', as: :assign_discount
    get  'recurring_reservations', on: :member
  end

  resources :companies do
    resources :admins, expect: [:new, :show]
    get :reports
    post :create_report
    get :report
    resources :invoices do
      collection do
        post :create_drafts
        post :send_all
        post :mark_paid
        post :destroy_all
        post :create_report
      end
    end
    get 'revenue' => 'dashboard#revenue', as: :revenue
    get 'resv' => 'dashboard#resv'
    member do
      post 'import_customers'
      get  'customers_csv_template'
    end
  end
  resources :invoices, only: [:show] do
    resources :invoice_components
    resources :custom_invoice_components
  end

  get 'companies/:id/customers' => 'companies#customers', as: :company_customers
  get 'venues/:id/map_users' => 'venues#map_users', as: :map_users

  resources :memberships, only: [:create] do
    collection do
      post :import
      get :csv_template
    end
  end

  resources :venues do
    resources :game_passes
    resources :prices, except: [:index, :new, :edit] do
      member do
        post :merge_conflicts
      end
    end
    resources :courts do
    end
    resources :reservations do
      get 'new_cart', on: :collection
      get  'resell_to_user_form', on: :member
      post 'resell_to_user', on: :member
    end
    resources :memberships, except: [:new, :edit, :update]
    get 'memberships/:id/convert_to_cc' => 'memberships#convert_to_cc', as: :convert_to_cc
    post 'memberships/:id' => 'memberships#update'
    get 'offdays'
    resources :day_off, only: [:create, :destroy]
    get 'court_modal/:id' => 'venues#court_modal', as: :court_modal
    get 'price_modal/:id' => 'venues#price_modal', as: :price_modal
    get 'closing_hours'
    get 'booking_ahead_limit'
    get 'active_courts'
    post 'change_listed' => 'venues#change_listed', as: :change_listed
    member do
      get 'reports'
      post 'booking_sales_report'
      get 'available_court_indexes'
    end
    resources :discounts, except: [:new]
    get 'manage_discounts', as: :manage_discounts
    get 'edit_emails'
    post 'update_emails'
    resources :photos, only: [:create, :destroy] do
      post 'make_primary'
    end
    resources :email_lists do
      post 'remove_users'
      post 'add_users'
      get 'off_list_users'
    end
  end

  post '/custom_mail(.:format)' => 'email_lists#custom_mail'
  get 'reservations/:id/cancel' => 'reservations#refund', as: :reservation_refund
  get 'reservations/:id/cancel_reservation' => 'reservations#cancel', as: :reservation_cancel
  get 'reservations/:id/resell' => 'reservations#resell', as: :reservation_resell
  get 'reservations/:id/show_log' => 'reservations#show_log', as: :reservation_show_log
  get '/privacypolicy', :to => redirect('/privacypolicy.html')
  get '/termsofuse', :to => redirect('/termsofuse.html')
end

app/views/shared/_booking_modal.html.erb
<div class="modal fade modal_center modal-booking" id="booking-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-booking__container">
    <button type="button" class="close close-modal" data-dismiss="modal" aria-label="Close">
      Close
    </button>
      <div class="modal-booking__header">
        <!--          <div class="modal-booking__icon"></div>-->

        <div class="modal-booking__icon venue-category">
          <div class="dropdown">
            <button class="venue-category__select" type="button" id="dropdown-cat-modal-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag 'icons/select2/tennis.svg' %>

            </button>
            <% if @venue.present? && @venue.try(:supported_sports).size > 1 %>
              <div class="dropdown-menu dropdown-menu-cats" aria-labelledby="dropdown-cat-modal-1">
                <% @venue.supported_sports.each do |sport| %>
                <% path = 'icons/select2/active/' + sport + '.svg' %>
                <a class="dropdown-item " id='<%= sport %>'><%= image_tag path %></a>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-16 col-sm-9">
            <div class="modal-booking__title"><%= @venue.try(:venue_name) %></div>
          </div>
          <div class="col-xs-16 col-sm-7">
            <div class="modal-booking__when form-inline">
            <span><%= t('.available_on')%></span><span class="form-group__append dropdown">
              <input type="text" class="modal-booking__datapicker js-datepicker__booking" <%= params[:date].present? ? "val='#{params[:date]}'" : ''%>/>
              <span class="form-group__appendix"><span class="icon-arrow-down-picker-booking"></span></span> </span>
            </div>
          </div>
        </div>


      </div>
      <div class="modal-booking__content js-accordion" id="available_times">
        <!-- MODAL CONTENT GOES HERE -->
      </div>
      <div class="modal-booking__footer">
        <div class="row">
          <div class="col-xs-16 col-sm-12">
            <div class="modal-booking__courts"></div>
          </div>
          <div class="col-xs-16 col-sm-4">
            <% if current_user %>
              <button class="btn btn-lg btn-primary" id="selectBookingsBtn" data-user-id="<%= current_user.id %>"><%= t('.book_button')%></button>
            <% else %>
              <button class="btn btn-lg btn-primary" id="showLoginModal"><%= t('.book_button')%></button>
            <% end %>
          </div>

        </div>

      </div>

    </div>
  </div>
</div>

app/views/shared/_booking_modal_content.html.erb
<div class="row">
  <div class="col-xs-16 col-md-5">
    <div class="modal-booking__list">

      <% i = 1 %>
      <% @available.to_h.each_pair do |key, value| %>
        <% time = DateTime.parse(key).strftime("%H:%M") %>
        <div class="modal-booking__list-one js-accordion_link" id="content-<%=i%>" data-time="<%=time%>" >
          <div class="row">
            <div class="col-xs-3 col-sm-3">
              <div class="hex-price hex-price_blue hex-price_sm">
                <sup class="hex-price__currency">€</sup>
                <span class="hex-price__val"><%= value['lowest_price'].to_i %>+</span>
              </div>
            </div>
            <div class="col-xs-3 col-sm-2">
              <div class="modal-booking__list-time"><%= time %></div>
            </div>
            <div class="col-xs-8 col-sm-9">
              <div class="modal-booking__list-text">
                <b><%= value['available_courts'].length %></b>
                <%= t('shared.booking_modal_content.available') %>
              </div>
            </div>
            <div class="col-xs-2 col-sm-2">
              <div class="modal-booking__list-arr">
                <span class="icon-arrow-right3"></span>
              </div>
            </div>
          </div>
        </div>
        <% i += 1 %>
      <% end %>

    </div>
  </div>
  <div class="col-xs-16 col-md-11">
    <div class="modal-booking__contents">
      <% i = 1 %>
      <% @available.to_h.each_pair do |key, value| %>
        <% time = DateTime.parse(key).strftime("%H:%M") %>
        <div class="modal-booking__contents-one js-accordion_content" data-id="content-<%=i%>" data-time="<%=time%>" data-datetime="<%=key%>">
          <div class="modal-booking__courts">
            <% value['available_courts'].each do |court| %>
              <div class="modal-booking__court modal-booking__court_white" data-id="<%= court['id'] %>" data-payment-skippable=<%= court['payment_skippable'] %>>
                <div class="modal-booking__court-title"><%= court['name'] %></div>
                <div class="modal-booking__court-des">
                  <span class="modal-booking__court-duration"><%= value['duration'] %></span>
                  min
                </div>
                <div class="hex-price hex-price_white hex-price_sm">
                  <sup class="hex-price__currency">€</sup><span class="hex-price__val"><%= court['price'] %></span>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        <% i+= 1 %>
      <% end %>

      <% if @available.to_h.keys.size > 0 %>
      <div class="modal-booking__contents-one modal-booking__contents-one-first js-accordion_content ">
        <div class="modal-booking__contents-nantitle"><%= t('shared.booking_modal_content.nantitle')%></div>
        <p class="modal-booking__contents-nantext"><%= t('shared.booking_modal_content.nantext_line1')%></p>
        <p class="modal-booking__contents-nantext"><%= t('shared.booking_modal_content.nantext_line2')%></p>
      </div>
    <% else %>
      <div class="modal-booking__contents-one modal-booking__contents-one-first js-accordion_content ">
        <div class="modal-booking__contents-nantitle"><%= t('shared.booking_modal_content.nofound_nantitle')%></div>
        <p class="modal-booking__contents-nantext"><%= t('shared.booking_modal_content.nantext_line1')%></p>
        <p class="modal-booking__contents-nantext"><%= t('shared.booking_modal_content.nantext_line2')%></p>
      </div>
    <% end %>
    </div>
  </div>
</div>


<%= javascript_tag do %>
  function sports_image(type) {
    var images  = {
      'squash': "<%= image_path('icons/select2/squash.svg') %>",
      'badminton': "<%= image_path("icons/select2/badminton.svg") %>",
      'tennis': "<%= image_path("icons/select2/tennis.svg") %>"
      }
    return images[type];
  }

  var image_url =  sports_image('<%= params[:sport_name] %>');

  $(".venue-category__select img").attr("src", image_url);

  $(".dropdown-menu-cats").on("click", 'a', function(event) {
     var sport_name = $(event.currentTarget).attr('id');
     $(".venue-category__select img").attr("src", sports_image(sport_name));

     var id = $('#venueId').val();
     var date = $('#searchDate').val();
     var time = $('#searchTime').val();
     var duration = $('#searchDuration option:selected').val();
     if ($('#selectUser').val() > 0) {
       var userId = $('#selectUser').val();
     } else {
       var userId = undefined;
     }
     $(".venue-category__select").val(sport_name);
     searchAvailable(id, date, time, duration, userId, sport_name);
  })

<% end %>

app/views/shared/_booking_success_modal.html.erb
<div class="modal modal_light fade modal_center modal_booking-successful" id="booking-successful-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal__container">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><i class="modal__close"></i></span></button>
            <div class="modal__header modal__header_withicon">
                <div class="icon-check"></div>
                <div class="modal__title"><%= t('.title') %></div>
            </div>
            <div class="modal__bubble"></div>
            <div class="modal__content">
                <p class="modal__text"><%= t('.text')%></p>
                <div class="btn-choose btn-choose_horizontal btn-choose_dark">
                  <%= link_to root_path do%><button class="btn btn-success"><%= t('.make_another')%></button><% end %><div class="btn-choose__or"><%= t('support.or')%></div><%= link_to t('.view_booking'), user_path(current_user), class: "btn btn-primary" if current_user %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_credit_card_modal.html.erb
<div class="modal modal_light fade modal_center modal_payment modal_payment-addnew" id="credit-card-modal" tabindex="-1" role="dialog" aria-hidden="true" data-backdrop="false">

  <div class="modal-dialog" role="document">
    <div class="modal__container">
      <div class="modal__header modal__header_withicon">
        <div class="icon-payment"></div>
        <div class="modal__title"><%= t('.title')%></div>
      </div>
      <div class="modal__content">
        <form>
          <div class="row">
            <div class="col-xs-15">
              <fieldset class="form-group">
                <input type="text" class="form-control" placeholder="<%= t('.card_number')%>" />
              </fieldset>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-16 col-sm-5">
              <fieldset class="form-group">
                <%= select_tag('', options_for_select(t('date.month_names')[1..-1].each_with_index.map { |m, i| [m, i+1] }), class: 'form-control js-select2') %>
              </fieldset>
            </div>
            <div class="col-xs-16 col-sm-5">
              <fieldset class="form-group">
                <select class="form-control js-select2">
                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                  <option value="5">5</option>
                  <option value="6">6</option>
                  <option value="7">7</option>
                  <option value="8">8</option>
                  <option value="9">9</option>
                  <option value="10">10</option>
                  <option value="11">11</option>
                  <option value="12">12</option>
                  <option value="13">13</option>
                  <option value="14">14</option>
                  <option value="15">15</option>
                  <option value="16">16</option>
                  <option value="17">17</option>
                  <option value="18">18</option>
                  <option value="19">19</option>
                  <option value="20">20</option>
                  <option value="21">21</option>
                  <option value="22">22</option>
                  <option value="23">23</option>
                  <option value="24">24</option>
                  <option value="25">25</option>
                  <option value="26">26</option>
                  <option value="27">27</option>
                  <option value="28">28</option>
                  <option value="29">29</option>
                  <option value="30">30</option>
                  <option value="31">31</option>
                </select>
              </fieldset>
            </div>
            <div class="col-xs-16 col-sm-5">
              <fieldset class="form-group">
                <input type="text" class="form-control" placeholder="<%= t('.card_cvc')%>" />
              </fieldset>
            </div>
          </div>

          <fieldset class="form-group">
            <button class="btn btn-primary btn-lg"><%= t('.submit_button')%></button>
          </fieldset>

          <fieldset class="form-group">
            <a data-dismiss="modal" aria-label="Close" href="#"><%= t('.cancel_button')%>></a>
          </fieldset>

        </form>
      </div>
    </div>
  </div>
</div>

app/views/shared/_login_modal.html.erb
<div class="modal modal_dark fade modal_center" id="login-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal__container">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><i class="modal__close"></i></span></button>
            <div class="modal__header modal__header_login">
                <div class="modal__logo"></div>
            </div>
            <div class="modal__content">
            <%= form_for(resource, as: resource_name, url: session_path(resource_name), :html => { :id => "form" })  do |f| %>
                    <fieldset class="form-group">
                        <%= f.email_field :email, autofocus: true, :class => "form-control", :placeholder => true %>
                    </fieldset>
                    <fieldset class="form-group">
                        <div class="form-group__append">
                            <%= f.password_field :password, autocomplete: "off", :class => "form-control", :placeholder => true %>
                            <span class="form-forgot"><%= link_to t('.forgot_password'), new_user_password_path  %></span>
                        </div>
                    </fieldset>
                    <fieldset class="form-group form-group_btns">
                        <div class="btn-choose btn-choose_horizontal btn-choose_dark">
                        <%= link_to user_omniauth_authorize_path(:facebook), class: "btn btn-primary-outline btn_lg js-save-selected-bookings", id:"fb-login" do %><span class="icon-fb_white"></span>&nbsp;<%= t('.login_fb') %><% end %><div class="btn-choose__or"><%= t('.or') %></div><button class="btn btn-primary btn_sm js-save-selected-bookings"><%= t('.login') %></button>
                        </div>
                    </fieldset>
                    <fieldset class="form-group">
                        <div class="modal__small"><%= t('.signup_message')%> <%= link_to t('.signup'), new_user_registration_path %></div>
                    </fieldset>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Amper</title>

    <!-- Main css styles -->
    <%= stylesheet_link_tag    'pages', media: 'all', 'data-turbolinks-track' => true %>

    <!-- Main javascript files -->
    <%= javascript_include_tag 'pages', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>



</head>
<body>

<div class="nav-container">
  <nav>
    <div class="nav-bar">
      <div class="module left">
        <ul class="menu">
          <li><%= link_to image_tag("http://ampersports.com/bookingimg/amperlogoblack.png", :height => "30"), "/" %> </li>
          <li class="divider">&nbsp;</li>
          <li class=""> <a href="#"> <%= image_tag 'gps.png', size: "20" %> Helsinki</a> </li>
          <li class="divider">&nbsp;</li>
          <li class="">
            <a href="#"><%= image_tag 'tennis.png', size: "20" %>&nbsp;&nbsp; Tennis</a>
          </li>
        </ul>
      </div>
      <div class="module-group right">
        <div class="module left">
          <ul class="menu">
          <% if (!user_signed_in?) %>
            <li> <%= link_to t("main_navbar.sign_up"), new_user_registration_path, :class => "btn btn-sm btn-rounded" %> </li>
            <li> <%= link_to t("main_navbar.sign_in"), new_user_session_path %></li>
          <% else %>
            <li><%= link_to current_user.first_name, user_path(current_user.id), class: "btn btn-sm btn-rounded" %></li>
            <li><%= link_to t("main_navbar.logout"), destroy_user_session_path, method: :delete  %></li>
          <% end %>
          <li>
            <a href="#"><%= t "main_navbar.help" %></a>
          </li>
          </ul>
        </div>
      </div>

    </div>
  </nav>
</div>
<!-- Main view  -->
<%= yield %>




</body>
</html>

app/views/shared/_newnav.html.erb
<header class="b-header">
  <nav class="navbar navbar-full navbar-light">
    <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#main-landing-navbar">
      &#9776;
    </button>
    <div class="collapse navbar-toggleable-xs" id="main-landing-navbar">
      <a class="navbar-brand_logo" href="/"></a>
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <div class="dropdown">
            <button class="nav-link btn-location" id="js-dropdown-location" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span class="icon-map"></span><span>Helsinki</span></button>
          </div>
        </li>
      </ul>
      <ul class="nav navbar-nav b-header-nav_right">
        <% if (!user_signed_in?) %>
        <li class="nav-item">
          <a class="b-header-btn" href="#" data-toggle="modal" data-target="#signup-modal"><%= t('.signup_html')%></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#" data-toggle="modal" data-target="#login-modal"><span class="icon-user"></span><span><%=t('.login_html')%></span></a>
        </li>
        <% else %>
        <li class="nav-item nav-item_emptyborder">
          <%= link_to user_path(current_user.id), class: "nav-link" do %>
          <span class="icon-user"></span><span><%= current_user.first_name %></span><% end %>
        </li>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
          <span class="icon-logout"></span><span><%= t('.logout') %></span><% end %>
        </li>
        <% end %>

        <li class="nav-item">
          <a class="nav-link" href="https://playven.zendesk.com/hc/fi"><span class="icon-help"></span><span><%= t('.help') %></span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://sales.playven.com"><span class="icon-help"></span><span><%= t('.get_playven') %></span></a>
        </li>
      </ul>
    </div>
  </nav>
</header>


<%= render 'shared/login_modal' %>
<%= render 'shared/signup_modal' %>

app/views/shared/_payment_modal.html.erb
<div class="modal modal_light fade modal_center modal_payment" id="payment-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal__container">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><i class="modal__close"></i></span></button>
      <div class="modal__header modal__header_withicon">
        <div class="modal__title"><%= t('.title')%></div>
      </div>
      <div class="modal__content">
        <div class="modal__text"><%= t('.book_text')%>
          <div class="js-courts-summary"></div>
          <div class="js-courts-summary-item-template hidden">
            <div class="row js-courts-summary-item">
              <div class="com-xs-9 col-sm-6 js-summary-item-name"></div>
              <div class="com-xs-3 col-sm-2 js-summary-item-price"></div>
              <div class="com-xs-12 col-sm-8 js-summary-item-game-pass">
                <select class="select2_demo_2 form-control" style="width: 100%" data-index='0'>
                  <option></option>
                </select>
              </div>
            </div>
          </div>
          <br/>
          <span class="js-courts-number"></span> <%= t('.court_count')%> <span class="js-courts-price"></span>
        </div>
        <form id='card-select-form'>
          <fieldset class="form-group">
            <div class="row card-select-row">
              <div class="com-xs-12 col-sm-8" id='card-select-div'>
                <% if current_user.has_stripe? %>
                  <%= render partial: 'users/credit_cards', locals: {cards: current_user.has_stripe? ? current_user.cards : nil } %>
                <% else %>
                  <span> <%= t('.no_card_msg')%> </span>
                <% end %>
              </div>
              <div class="com-xs-12 col-sm-8">
                <input id="add-card"
                       class="btn btn-secondary btn-lg modal__addcard strp-btn"
                       type="submit"
                       value="<%= t('.submit_button')%>"
                       data-stripe-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                       data-stripe-locale="auto" data-user-url="<%= user_add_card_path(current_user) %>" />
              </div>
            </div>
          </fieldset>
          <fieldset class="form-group">
            <button class="btn btn-primary btn-lg" id="makeReservationBtn" <% if !current_user.has_stripe? %> disabled <% end %>><%= t('.pay_button')%></button>
						<%= render partial: 'shared/spinner_circle', locals: { id: 'pay-spinner' } %>
          </fieldset>
          <p class="modal__small"><a href="#" id="makeReservationUnpaid"><%= t('.skip_payment') %></a></p>
        </form>
      </div>
    </div>
  </div>
</div>


<script src="https://checkout.stripe.com/checkout.js"></script>

app/views/shared/_signup_modal.html.erb
<div class="modal modal_dark fade modal_center" id="signup-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal__container">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><i class="modal__close"></i></span></button>
            <div class="modal__header modal__header_signup">
                <div class="modal__logo"></div>
            </div>
            <div class="modal__content">
                <%= form_for(resource, as: resource_name, url: registration_path(resource_name), :html => { :id => "signup-form" }) do |f| %>
                    <fieldset class="form-group">
                        <div class="row">
                            <div class="com-xs-12 col-sm-8"><%= f.text_field :first_name, :class => 'form-control', :placeholder => true, autofocus: true %></div>
                            <div class="com-xs-12 col-sm-8"><%= f.text_field :last_name, :class => 'form-control', :placeholder => true, autofocus: true %></div>
                        </div>
                    </fieldset>
                    <fieldset class="form-group">
                        <%= f.email_field :email, autofocus: true, :class => "form-control", :placeholder => true %>
                    </fieldset>
                    <fieldset class="form-group">
                        <%= f.password_field :password, :class => 'form-control', :placeholder => true,  autocomplete: "off" %>
                    </fieldset>
                    <fieldset class="form-group">
                        <%= f.password_field :password_confirmation, autocomplete: "off", :class => "form-control", :placeholder => true %>
                    </fieldset>
                    <fieldset class="form-group form-group_btns">
                        <div class="btn-choose btn-choose_horizontal btn-choose_dark">
                            <div class="btn-choose btn-choose_horizontal btn-choose_dark">
                            <%= link_to user_omniauth_authorize_path(:facebook), class: "btn btn-primary-outline btn_lg js-save-selected-bookings" do %><span class="icon-fb_white"></span>&nbsp;<%= t('.sign_up_fb') %><% end %><div class="btn-choose__or"><%= t('.or') %></div><button class="btn btn-primary btn_sm js-save-selected-bookings"><%= t('.sign_up') %></button>
                            </div>
                        </div>
                    </fieldset>
                <% end %>
                <p class="modal__small"><%= t('.terms_accept_html', link: 'http://www.ampersports.com/toc.html')%></p>
            </div>
        </div>
    </div>
</div>